### ISSUE TITLE
Keep getting "document" is not defined. Do I have to make a document with jsdom?

### ISSUE THREAD

**Issue by nackjicholson** [jquense/teaspoon#12]
Trying something similar to this from your $.fn.render docs:

```js
$(<Component/>).render().trigger('click', { target: { value: 'hello ' } }).
```

Does not like.

```
     ReferenceError: document is not defined
      at QueryCollection.render (node_modules/teaspoon/element.js:57:31)
      at Context.<anonymous> (Component.test.js:1:2)
```

**Comment by nackjicholson** [comment]
I fixed it with this helper fixture, but I'd like to know what your approach is.

*createDocument.js*

```
import { jsdom } from 'jsdom';

function createDocument() {
  const document = jsdom(undefined);
  const window = document.defaultView;
  global.document = document;
  global.window = window;

  Object.keys(window).forEach((key) => {
    if (!(key in global)) {
      global[key] = window[key];
    }
  });

  return document;
}

export default createDocument;
```

So now I call `createDocument()` before trying to render with teaspoon.

I feel like I must be missing something this doesn't seem like the way. :confounded:

**Comment by jquense** [comment]
Hi there, 

I'd like to keep the environment flexible and not force someone to to use jsdom or whatever. In my own case I generally use jsdom with karma which is mostly the same as what you've figured out above. 

I do need to improve the docs with some testing env stuff and this is a great addition to that, if you don;t mind me using this :)

**Comment by nackjicholson** [comment]
No, not all. I could also try to clean this up, and more broadly applicable and then make a documentation pull request if you'd rather.

**Comment by brvenkat** [comment]
Is this issue fixed? I still see the problem when trying to render, still keep getting a document not defined error

teaspoon/element.js:89
    var mount = mountPoint || document.createElement('div'),
                           
ReferenceError: document is not defined

**Comment by farynaio** [comment]
Aibnb guys, also described how to configure jsdom in [Enzyme doc](http://airbnb.io/enzyme/docs/guides/jsdom.html), it's quite similar to @nackjicholson solution.

**Comment by kadirisani** [comment]
I tried the solution suggested by @nackjicholson and it worked for me!
