### ISSUE TITLE
.text() always seems to return ""

### ISSUE THREAD

**Issue by thom-nic** [jquense/teaspoon#13]
Apologies in advance for being vague but I'll do the best I can to describe what I'm seeing.  I deleted and re-installed my `node_modules`, some package got a patch-level version bump (I define dependencies like `"^1.0.0"`) and now the following fails:

```
  it('text() and innerText are equal', () => {
    const $root = $(<div className="foo"><span className="bar">textme!</span></div>).render();
    const inner = $root.first('.bar');
    expect(inner.text()).toBe(inner.unwrap().innerText);  // Expected '' to be 'textme!'.
  });
```

Also seeing a lot of this warning:
```
WARN: 'iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error: 
```
which may be completely unrelated but popped up at the same time.

Here's my [dependency list and npm ls tree](https://gist.github.com/thom-nic/dcbd67473b27716f37a8)

**Comment by thom-nic** [comment]
Just noticed that if I use `shallowRender`, then the previous example works.  But then we're obv not rendering into the DOM and lots of testing/ verification code has to change.  Hopefully that helps narrow down the source...

**Comment by thom-nic** [comment]
... and the `iterable.length` warnings come from doing something like the following:

```javascript
    const $root = $(<ErrorMessage errors={errors}/>).render();
    console.log($root.length);
```
Only when rendering a react component - doesn't happen if you render `$(<div className='foo'/>).render().length`

**Comment by jquense** [comment]
well the iterable stuff is definitely not teaspoon, its probably from immutable.

I'll take a look at test issue, I made some substantial changes to a dep in teaspoon, and there may be a regression there. let me investigate. thanks for the heads up

**Comment by jquense** [comment]
pushed an update to `bill` so reinstall teaspoon, and confirm you have its sub dep of bill@1.5.1 and let me know if the problem goes away?

thanks again

**Comment by thom-nic** [comment]
Thanks for the quick response.  That seems to have fixed move of the problem, but I'm still seeing two errors, both with this error:
```
	TypeError: 'undefined' is not an object (evaluating '_ref.props.className')
```
It's being thrown on a line like this:
```javascript
    const $root = $(<ErrorMessage errors={errors}/>).render();
    expect($root.find('button.close').length).toBeGreaterThan(0);   // throws error
```

**Comment by thom-nic** [comment]
Also, regarding the iterable error, I *am* using immutableJS - is it possible teaspoon is iterating over an immutable collection assigned to one of my components' `props`?  Either that or react itself is using immutable internally maybe.  I'm not calling `.length` in my component code, it happens when I call teaspoon's `ElementCollection#length`.  Either way, it seems teaspoon is calling `.length` on an immutable collection which is triggering the warning.

**Comment by jquense** [comment]
Any chance you can post the content of <ErrorMessage /> and its props so I can reproduce it?

**Comment by jquense** [comment]
I actually think I can guess at the issue, and it may be related to both, are you using an immutable map/list as children somewhere?

**Comment by thom-nic** [comment]
Yup.  I'm AFK but can post source code tonight.

**Comment by jquense** [comment]
u[dated bill again, let me know!

**Comment by thom-nic** [comment]
Yup, that looks like it fixed it.  Thanks the the quick turnaround!
