### ISSUE TITLE
Double element present for nested components

### ISSUE THREAD

**Issue by smazurov** [jquense/teaspoon#14]
## The Problem

I use [`react-toolbox`](https://github.com/react-toolbox/react-toolbox) for my styling and I have come across an issue that might be related to `teaspoon` (or might be a bunch of other things :cry:). `react-toolbox` uses composed components for [`Button`](https://github.com/react-toolbox/react-toolbox/blob/dev/components/button/Button.jsx#L81) which adds a ripple effect to whatever component you pass it. 

doing a `$(<TestComponent/>).render()` and running a `single()` expectation fails:

```
  Test Component
    Structure Tests
      1) should display one button


  0 passing (154ms)
  1 failing

  1) Test Component Structure Tests should display one button:
     Error: The query found: 2 items not 1
```

My component is very simple:

```js
import React from 'react';
import Button from 'react-toolbox/lib/button';

const TestComponent = props => {
  return (
    <div>
      <Button type="submit" label="Test" />
    </div>
  );
};

export default TestComponent;
```

my test, is also simple:

```js
import $ from 'teaspoon';
import React from 'react';
import TestComponent from './TestComponent';

describe('Test Component', () => {
  describe('Structure Tests', () => {
    const element = $(<TestComponent/>).render();

    it('should display one button', () => {
      element.find('button[type="submit"]').single();
    });
  });
});
```

if I switch to `shallowRender()` it finds 0 elements, or use `true` in `render(true)`, it still doesn't work.

Running this on the server, only one `button` element is present:

```html
<div data-reactid=".1rnwfp9pts0" data-react-checksum="-1143472991">
  <button type="submit" class="_node_modules_react_toolbox_lib_button_style__flat _node_modules_react_toolbox_lib_button_style__neutral" data-react-toolbox="button" data-reactid=".1rnwfp9pts0.0">
    <span data-reactid=".1rnwfp9pts0.0.1">Test</span>
    <span data-react-toolbox="ripple" class="_node_modules_react_toolbox_lib_ripple_style__wrapper" data-reactid=".1rnwfp9pts0.0.2:1">
      <span role="ripple" class="_node_modules_react_toolbox_lib_ripple_style__normal" style="transform:translate3d(0px, 0px, 0) scale(1);-webkit-transform:translate3d(0px, 0px, 0) scale(1);-ms-transform:translate3d(0px, 0px, 0) scale(1);" data-reactid=".1rnwfp9pts0.0.2:1.0"></span>
    </span>
  </button>
</div>
```

## The Repro steps:

I have created a [repository](https://github.com/smazurov/teaspoon-toolbox-bug) to demonstrate the issue.

1. Clone the repo: `git clone https://github.com/smazurov/teaspoon-toolbox-bug.git`
2. `npm install`
3. `npm test`
4. `node server` to confirm single element in html.

## Affected versions

I tested this with `teaspoon` 5 and 6, and they both exhibited the same issue.

### Caveats

Other components that do not compose themselves (such as `<Input />`) have no issues.

I am continuing to debug, and I need to rule out `jsdom` as a culprit, as rendering it in the browser/server, shows a single element.

------

Perhaps somebody can offer a clue as to how `render()` works in conjunction with selectors and if thats something that could happen under some unforeseen (to me) circumstances.

**Comment by jquense** [comment]
I think the issue is that the selector engine is ignoring case when looking at the component types.

So its returning the DOM component (`<button>`) and the "composite" component `<Button>`. If so that is definitely a bug. you can try to qualify the selector with the `:dom` pseudo (`button[type=submit]:dom`) and see if that helps.

**Comment by jquense** [comment]
I pushed a new release of the selector engine, can you nuke and reinstall teaspoon (ensuring it installs the latest `bill@2.1.1` pacakge) and see if that fixes the issue for you?

**Comment by smazurov** [comment]
I will check tomorrow. I didn't consider dom/composite both showing up, thanks for the tip!

**Comment by jquense** [comment]
take your time :P thanks for the super detailed and thorough issue, made my job much easier :)

**Comment by smazurov** [comment]
Confirmed, `:dom` fixed it as well as updating to `bill@2.1.1`. Thanks for the quick fix.

**Comment by Sinistralis** [comment]
I am experiencing this using a class selector with React-Bootstrap's Listview element. The component is a stateless component only containing the ListView. My test is as follows:

`import React from 'react';
import $ from 'teaspoon';
import expect from 'expect';

import { emptyList } from '../../src/utils/mockUtils';
import ReservedSessionSelect from '../../src/Components/ReservedSessionSelect';

describe('ReservedSessionSelect', () => {
  it('renders', () => {
    const $elements = $(
      <ReservedSessionSelect reservedSessions={emptyList}/>
    );

    const rendered = $elements.render();
    const reservedSessionSelect = rendered.find('.reservedSessionList');

    reservedSessionSelect.map((wat) => console.log(wat));

    expect(reservedSessionSelect.length).toBe(1);
    rendered.unmount();
  });
});
`

I get the same error of " Expected 2 to be 1"

**Comment by jquense** [comment]
@Sinistralis `2` makes sense in this case, since two components actually have that class the `Col` and the `div` the Col generates. If you are only interested in DOM nodes with the class consider using `.find('.myclass:dom')` or if you just want the Col component `.find('Col.myclass')`

**Comment by Sinistralis** [comment]
I see. I wasn't aware render worked like that. Good to know. I was looking for why this test need :Dom and realized our container tests all use divs. This makes sense now. Thanks for the prompt reply and the awesome library

**Comment by jquense** [comment]
No problem, its a subtle thing to remember, you aren't querying the DOM, you are querying the props/state of the react component hierarchy, which contains custom components and DOM node components, with some amount of duplication.

btw, If you were using shallowRendering the "div" inside the Col wouldn't be rendered so your test would have passed. more subtle distinctions
