### ISSUE TITLE
$(el).render() should accept more parameters like TestUtils

### ISSUE THREAD

**Issue by ngduc** [jquense/teaspoon#21]
$(el).render() should accept more parameters like TestUtils.

Use case:
const { intl } = intlProvider.getChildContext(); // react-intl
const renderer = TestUtils.createRenderer();
renderer.render(reactEl, { intl }); // *** this accepts the second parameter

Could you make $(el).render() to accept { intl } like the above function? Thanks.

**Comment by jquense** [comment]
Render does take context as an argument.

`$(el).render(context)`

**Comment by ngduc** [comment]
@jquense Thanks! That works!
