### ISSUE TITLE
Should use window.HTMLElement insead of HTMLElement

### ISSUE THREAD

**Issue by ngduc** [jquense/teaspoon#22]
Hi, thanks for this great library.
I'm using jsdom and got an error in teaspoon element.js:
ReferenceError: HTMLElement is not defined

If I use window.HTMLElement in element.js, the error goes away
```
if (mountPoint && !(mountPoint instanceof window.HTMLElement)) {
      context = mountPoint;
      mountPoint = null;
    }
```
Could you add "window" before HTMLElement to make it work with jsdom? Thanks.
Reference: (please see the last comment, not mine)
https://github.com/tmpvar/jsdom/issues/1170

**Comment by jquense** [comment]
I'd accept a pull request changing this, but I think the issue may be not correctly initializing the enviroment by creating a `window` and then coping all properties on it to `global` (the node equivalent)

**Comment by ngduc** [comment]
I tried to setup like this & it works but it doesn't look good to have HTMLElement in global.
```
import { jsdom } from 'jsdom';
global.document = jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;
global.navigator = global.window.navigator;
global.HTMLElement = global.window.HTMLElement;
```

I created a PR instead to use window.HTMLElement. Please merge. Thanks.

**Comment by nackjicholson** [comment]
Have these changes actually been released?

**Comment by jquense** [comment]
yes
