### ISSUE TITLE
`$.fn.eq()` would be nice

### ISSUE THREAD

**Issue by maackle** [jquense/teaspoon#24]
related to #9 - it would be handy to have functionality similar to jQuery's `eq`:

``` js
$list = $(<ul><li/><li/></ul>);
$items = $list.find('li');
$items.eq(0) === $($items[0]);
```

I could submit a pull request if this isn't already addressed somewhere. Seems trivial, just an alias.

**Comment by jquense** [comment]
Funny you should ask, I've actually got an implementation of `nth()` on a local branch here, so this should be covered in the next release (soon hopefully).

**Comment by maackle** [comment]
Great!

**Comment by tgirardi** [comment]
@jquense I see that `nth` is available in the last version. However, it is missing in the documentation.

Also. This issue could probably be closed

**Comment by jquense** [comment]
it reminds me I still need to document it ;) PR's welcome on that front
