### ISSUE TITLE
.find doesn't find appropriate elements from .dom() in some cases

### ISSUE THREAD

**Issue by davejacobs** [jquense/teaspoon#25]
I've run into a problem where `.find` doesn't return some elements that show up in `.dom()`. Specifically, it happens to me when the DOM changes during the test. Any idea why this is? Maybe `.find` is caching the initial state of the rendered component?

I'd love to figure this out so I can introduce teaspoon into our codebase. (So far, trying out the library has been a great experience.)

Example failing spec:

```javascript
import React from 'react';
import t from 'teaspoon';

class ExampleComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = { showText: false };
  }

  render() {
    const textSpan =
      this.state.showText ?
        <span className='text' onClick={this.props.onClickText}>
          Hidden Text
        </span> :
        null;

    return (
      <div>
        <h1 className='header' onClick={this.handleHeaderClick.bind(this)}>
          Show Text
        </h1>
        {textSpan}
      </div>
    );
  }

  handleHeaderClick() {
    this.setState({ showText: true });
  }
}

describe('ExampleComponent', () => {
  it('when I click the hidden text, it fires its click handler', () => {
    const clickSpy = jasmine.createSpy('click spy');

    const component = t(
      <ExampleComponent onClickText={clickSpy} />
    ).render();

    component.find('.header').trigger('click');
    // Examining component.dom() here does show '.text', but
    // querying for it returns 0 items.
    component.find('.text').trigger('click');

    expect(clickSpy).toHaveBeenCalled()
  });
});
```

**Comment by jquense** [comment]
thanks for the issue I'll take a look.  could you also make sure you have the newest teaspoon installed? you may have to remove completely first to make sure that a fresh install gets you the newest versions of its dependencies (specifically `bill`) which happened the element traversals

**Comment by davejacobs** [comment]
I've tried removing from `node_modules` and re-installing and am still seeing the same issue. Thanks for looking into it!

**Comment by jquense** [comment]
ok install the latest, should be fixed

**Comment by davejacobs** [comment]
Awesome, thanks!
