### ISSUE TITLE
Difficulty testing dynamic components

### ISSUE THREAD

**Issue by Sinistralis** [jquense/teaspoon#26]
I'm having issues with writing a unit test for a component that changes the html its rendering.

https://gist.github.com/Sinistralis/853d8ae219f8ecb61f7d

I just can't get the bottom test to work. I've been trying different combinations but nothing is giving me the behavior I am looking for.

The idea is that the component renders a button. When the button is clicked, it calls props.showSessionOptionsModal and is passed true or false.

So the point of the test is that a modal selector should return nothing before the click, and something after. No matter what I do though, it always returns 2 items. I've tried selecting by the Modal component and the .modal class (Bootstrap-React for reference).

This is likely an issue on my end, but I ran into the same problem with popovers (which have the same behavior of existing only after a click, but a selector always grabbing them). Am I missing something or am I running into a bug?

I'd like to write a little guide on this library so I've been striving to write more.. useful tests and this is a problem I seem to encounter again and again.

**Comment by jquense** [comment]
Its hard to know by looking at the gist but if your issues are with Modals/overlays the difficultly is probably due to how they are implemented, since they both render the actual body of the overlay in a __different__ react hierarchy or tree (see the Portal pattern for more info).

For things returning double what you expect, that's usually a little gotcha with how rendered component trees work. Teaspoon queries again the react tree, not the DOM, so if you are looking for something with a `.modal` class, its checking `props.className` not the node classes, so you usually get the Custom component and the DOM Component it renders. Try the selector with `:dom` or `:composite` depending on which one you are interested in.

**Comment by Sinistralis** [comment]
Yea, you mentioned that to me earlier and that works fine when evaluating, but it still duplicates console logs for some reason.

You're assumption with the Portal pattern is correct, both modals and arrays render using the portal pattern. Is there something special I need to do to accomodate for this?

**Comment by Sinistralis** [comment]
Playing around with React devtools and I think I was working under some wrong assumptions. Give me a few.

**Comment by jquense** [comment]
teaspoon doesn't have anything specifically to deal with Portals. I'd love to do soemthing, and plan on it, but its not an easy problem, there isn't any good way of knowing when a component renders into a subtree. Generally the way to handle portals in tests is provided by the implementation itself. 

If you are jsut making assertions about the DOM I would use document.querySelectorAll, or in the case of react-bootstrap, it exposes (sort of) useful refs for reaching the inner components: `inst._wrapper` and `inst._backdrop` you can access those and wrap em in tsp() to keep on querying

**Comment by Sinistralis** [comment]
Y'know, I was trying to wrap my head around portals a few weeks back and couldn't figure it out, but your explanation just now made it completely click for me. Tests are working great. Here's the code for anyone interested:

https://gist.github.com/Sinistralis/fc09a3eb91685256f430

If there is anything I can do to help you with this project, let me know. We use this daily at my company and it's been the solution to React unit tests I've always wanted.

**Comment by Sinistralis** [comment]
Closing this so I don't clutter up your issues. Need to document this until portals are handled better.

**Comment by jquense** [comment]
Glad its working for ya'll :) 

I don't know that I have any specific things that are helpful besides telling folks about it and reporting when it doesn't help use cases you have. Feel PR stuff if you think they are generally helpful!

thanks!

**Comment by Sinistralis** [comment]
Could you clear up how to convert a querySelector result set to teaspoon? I am trying to do $([result]) but it doesn't seem to be working the way I expect. I am calling .each on that and it's not working quite right.

**Comment by jquense** [comment]
you can't right now (and maybe never) because there is no reasonable way to get a react instance from an arbitrary DOM node, which is why the subtree limitation is even more annoying then it might appear.

**Comment by Sinistralis** [comment]
Ok, sounds like I am going to have better luck having the modal contents be it's own component so I can actually render that to test it since I need to trigger React's synthetic events in my test. Whew, this has been a doozy.
