### ISSUE TITLE
Accessing root node after shallow rendering

### ISSUE THREAD

**Issue by dchambers** [jquense/teaspoon#3]
Do you know if there's a more convenient way of getting the root node when shallow rendering than this?:

```js
component.shallowRender()[0];
```

Maybe this would be better?:

```js
component.shallowRender().node();
```

Also, could you explain why an array is returned anyway, when my understanding is that you can only have one top-level node. For example, if I try to render more than one top-level component then I get this error:

```
Adjacent JSX elements must be wrapped in an enclosing tag
```

Am I missing something?

**Comment by jquense** [comment]
sure, the collection structure is modeled after jQuery partly because its an elegant model and partly because the api is probably a bit more familiar to folks. While you can't render more than one top node (at the moment), you use the same data structure as you traverse through the elements you can have collections of nodes like this:

```js
$([<div/>, <div/>, <div/>]).length // 3
```
or more likely:
```js
$(<MyComponent/>).shallowRender().find(':dom')  // probably returns more than 1!
```

So in both cases you end up with a bunch of elements in the array. In terms of your original question there isn't a specific method for unwrapping a single node but you could add one easily

```js
$.fn.node = function(){
  return this.single()[0]
}

$(<MyComponent/>).shallowRender().node()
```

**Comment by dchambers** [comment]
Hi @jquense,

Thanks for the very thorough explanation. All makes sense now. 

> In terms of your original question there isn't a specific method for unwrapping a single node but you could add one easily

> ```js
$.fn.node = function(){
  return this.single()[0]
}

> $(<MyComponent/>).shallowRender().node()
```

Are you not tempted to add one to library itself?  If you take a look at a typical test that uses shallow rendering then you'll see that this leaves an unapealling wrinkle in an otherwise very nice test, for example:

```js
it('removes the items list and footer when the last item is removed', function() {
  // given
  var todoApp = $(<TodoApp model={model}/>);

  // when
  todoApp.render().find('.destroy').trigger('click');

  // then
  expect(todoApp.shallowRender()[0], 'to have rendered with all children',
    <Container componentName="TodoApp">
      <TodoHeader/>
    </Container>
  );
});
```

**Comment by jquense** [comment]
that's fair, I myself am pretty used to that from jQuery, but we already have a `.dom()` method that unwraps the array so it makes sense to have an analog method for getting the element/instance.

**Comment by dchambers** [comment]
Lovely, thanks @jquense :+1:

**Comment by dchambers** [comment]
Hi @jquense, 

Now that I'm a bit more comfortable with the code I'm thinking of submitting a pull-request for this. Would you preference be for a `node()` method which errors if there's more than one item in the list, or a `first()` method which doesn't? Or, something else entirely?

**Comment by dchambers** [comment]
Okay, I've taken a [punt](https://github.com/jquense/teaspoon/pull/8) on this and assumed we'd want to fail-fast if more than one node exists.

**Comment by dchambers** [comment]
Hi @jquense, any chance you could release a new version to NPM so we can start using this and the shallow rendering fix?

**Comment by jquense** [comment]
yup there you go

**Comment by dchambers** [comment]
Thanks @jquense.
