### ISSUE TITLE
Certain code doesn't get ran

### ISSUE THREAD

**Issue by Sinistralis** [jquense/teaspoon#32]
Given the following code:

![image](https://cloud.githubusercontent.com/assets/2118069/14071626/e55012b6-f484-11e5-8e2a-9a1a88d12572.png)

I am testing Question just fine via shallow rendering.

When I try to test Answer with either shallow rendering or deep rendering, I am always being returned a length of 1 even though I am passing it an array of size > 1. It's like the .map never gets ran.

Is this something you can shed more light on?

**Comment by Sinistralis** [comment]
If I switch my test over to a .only(), it correctly finds N instances, but length and .get() both return only 1. If I try unwrap, I get 2.

So, my selector isn't returning the right thing or I am missing something. Here is an example of the selector:

`  it('Renders Answer', () => {
    const $elements = $(
      <QuestionEditor
        currentQuestion={initialState.get('currentQuestion')}
      />
    );

    $elements
      .shallowRender()
      .find('Answer:composite')
      .get();

    expect($elements.length).toBe(2);
  });`

**Comment by Sinistralis** [comment]
Apparently if I chain .length, it will work. But if I assign the .find to a variable and call .length on it, I get 1 instead of 2.

I'm happy it works but it doesn't make sense to me.

**Comment by Sinistralis** [comment]
Final working code:

```
  it('Renders Answer', () => {
    const $elements = $(
      <QuestionEditor
        currentQuestion={initialState.get('currentQuestion')}
      />
    );

    const count = $elements
      .shallowRender()
      .find('Answer:composite')
      .length;

    expect(count).toBe(initialState.getIn(['currentQuestion', 'answers']).size);
  });
```

**Comment by jquense** [comment]
thanks for all the derails tho I'm a bit unsure what the vroekn version looks like, could you post what you tried to do first so I can see the difference and maybe see why it didn't work?

**Comment by Sinistralis** [comment]
https://gist.github.com/Sinistralis/2f6ca70ed8de179caee5

Thats the code in question where one test is working and one is failing. Specifically, it's "Renders Question".

Note that the initialState code has more to it (like exports) but I just showed you what that object was so you could see.

**Comment by jquense** [comment]
Sorry its early for me, so "it Renders Question" is not working? but "it renders Answer" does work? Is there any way you can trim the test cases down to something I can run so I can really inspect it?

**Comment by Sinistralis** [comment]
I might be able to but it wouldn't be until Wednesday likely. I'll keep looking into it until then. I understand chucking code at you isn't going to help much, I just can't fathom what's going on here.

**Comment by Sinistralis** [comment]
So, found the issue. The Component inner Question on View was misspelled as Questoin. and it's a default export to I am guessing you do some kind of type check and it uses the class name as opposed to what it was exported as. 

I had a feeling it was something on my end. Sorry for the inconvenience. I'll close this. I still can't explain the .length but after that I'll bet it was something on my end.
