### ISSUE TITLE
 teaspoon document not defined error

### ISSUE THREAD

**Issue by brvenkat** [jquense/teaspoon#35]
I see a problem when trying to render a react component using teaspoon, keep getting a document not defined error

```
let instance = $(<div className='test'/>).render();
t.equal(instance.find('div.test').length, 1, 'Test Passed');
```

teaspoon/element.js:89
var mount = mountPoint || document.createElement('div'),

ReferenceError: document is not defined

**Comment by jquense** [comment]
are you using it in a browser setting? If not are you setting up something like jsdom? If you want to use normal rendering you need a document!

**Comment by brvenkat** [comment]
I am trying to write a unit test for my react component, i am not using it in browser setting

**Comment by jquense** [comment]
gotcha, you issue isn't teaspoon related actually. you need to use shallowRender or set up a mock DOM gotchenvironment, see the answer to that other issue you posted in there was a solution there using Jsdom.
