### ISSUE TITLE
$.fn.val

### ISSUE THREAD

**Issue by jacobp100** [jquense/teaspoon#36]
When simulating a change in a `<select>` element, it seemed to not be sufficient to call `$element.trigger('change', { currentTarget: { value: '0' } })`. It seems if you set the `value` on the dom node, then trigger `change` with no data, it works.

Reference: https://github.com/jquery/jquery/blob/master/src/attributes/val.js

**Comment by jquense** [comment]
you want to pass through target not currentTarget, I think. under the hood teaspoon is using the react test utils here so anything that works with that simulate would work here
