### ISSUE TITLE
0.18.3 -> 0.19.0 regressionwith .text()

### ISSUE THREAD

**Issue by jacobp100** [jquense/teaspoon#38]
I wasn’t able to isolate a test case.

Upgrading broke an existing test using `.text()`, which is now returning the string `’[object Object][object Object]’`, despite the HTML looking fine.

```js
console.log($testElement.dom().outerHTML, $testElement.text());
// <td><!-- react-text: 17 -->100.0<!-- /react-text --><!-- react-text: 18 --> miles<!-- /react-text --></td>
// [object Object][object Object]
```

**Comment by jquense** [comment]
fixed. the issue was actually with changes in React 15.2

**Comment by jacobp100** [comment]
Working now. Thanks!
