### ISSUE TITLE
Trigger on Shallow Render does not Bubble

### ISSUE THREAD

**Issue by jacobp100** [jquense/teaspoon#39]
``` js
const onChange = sinon.stub();
const $element = (
  <div onChange={onChange}>
    <input/>
  </div>
);

$element.find(`input`).trigger(`change`);

expect(onChange.called).toEqual(true);
```

**Comment by jquense** [comment]
you are correct! For the moment there is no real way for doing anything about that without writing a javascript implementation of the entire DOM event system, which is fairly out of scope for this little project.
