### ISSUE TITLE
Default context resets when using props()

### ISSUE THREAD

**Issue by NullDivision** [jquense/teaspoon#40]
When I create a component and render it the context is fine. Once I update props it gets removed.

My code looks like this:

```
tape('<MyComp /> should reset state on close', (t) => {
  let props = cloneDeep(DEFAULT_PROPS);
  props.open = true;

  $(<MyComp {...props} />)
    .render(false, undefined, { some: 'context' })
    .state('user', { surname: 'aee6d39c-b9aa-44ac-b463-0250b5542abe' })
    .props({ ...props, open: false })
    .tap((collection) => {
      t.looseEquals(collection.state('user').surname, '', 'resets state on close');
      t.end();
    });
});
```

Versions:
React - 15.3.0
Teaspoon - 6.4.1

**Comment by jquense** [comment]
`context` or `state` resets? I don't see any use of context here

**Comment by NullDivision** [comment]
Context. I've updated the example render method. As soon as the code reaches `.props({ ...props, open: false })` I get an error saying context is undefined.

I also tried doing `$.defaultContext({ some: 'context' })` but that didn't work at all.
