### ISSUE TITLE
find() function doesn't return results if component wrapped in provider component

### ISSUE THREAD

**Issue by NullDivision** [jquense/teaspoon#41]
Given I have a non-rendering component, specifically `MuiThemeProvider` from Material-UI:

```
  render() {
    return (
      <MuiThemeProvider muiTheme={muiTheme}>
        <Dialog open={true}>
          { /* content goes here */ }
        </Dialog>
      </MuiThemeProvider>
    );
  }
```

Running `$(<MyComp />).shallowRender().find(Dialog).length` returns nothing. Doing a console log of `$(<MyComp />).shallowRender().props('children').props.children` however reveals that the Dialog component is indeed a part of the stack.

**Comment by jquense** [comment]
Can you put together a generic reproduction so that I can try and debug it? anything i've tried works just fine.

**Comment by NullDivision** [comment]
Ok. Moved it to a separate class and tried to find the Dialog and it worked. What wasn't working is getting the action buttons to display but I'm guessing it's just shallow render not executing on Dialog directly so it's not passing it along.

Sorry for the false alarm. Closing the bug.

For anyone else that might make my mistake the shallow test for it is:
```
$($(<MyComp />).find(Dialog).props('actions')[0])
```
