### ISSUE TITLE
New React Dom Version completely breaks Teaspoon

### ISSUE THREAD

**Issue by Sinistralis** [jquense/teaspoon#42]
Teaspoon seems to be pulling in the latest version of react-addons-test-utils automatically which seems to be incompatible with previous versions of react-dom.

**Comment by Sinistralis** [comment]
Forked this and hosted a private version for my company. All I had to do was update the dependency on React to be set at 1.3.1 (the version we are currently on) and it works.

Also a note, this library doesn't work even with the proper 1.4 deps.

**Comment by jquense** [comment]
fixed in latest release
