### ISSUE TITLE
15.4.1 issue with ReactMount

### ISSUE THREAD

**Issue by logotype** [jquense/teaspoon#43]
Hi

Getting the following error after updating to latest teaspoon.

ERROR in ../~/teaspoon/utils.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in h:\<project name>\node_modules\teaspoon

**Comment by jquense** [comment]
yeah that's to be expected, it should result in any really issue it's a result of a dynamic require and needed to support all of react v15

**Comment by kirillkostko** [comment]
I use React v14, but I'm also getting the same error:

```
ERROR in ./~/teaspoon/utils.js
Module not found: Error: Cannot resolve module 'react-dom/lib/ReactMount' in C:\<project name>\node_modules\teaspoon
```

**Comment by cellog** [comment]
it's killing my entire test suite.  Is there any workaround?

**Comment by jquense** [comment]
its not a bug, The warning is unavoidable, but shouldn't break anything. webpack can work just fine with missing modules.

**Comment by logotype** [comment]
while a regular build test does work fine, it does cause issues when running tests in "watch" mode. when the error is thrown, the bundle is not rebuilt.

**Comment by jquense** [comment]
push a code change that makes sure webpack downgrades this to a warning, and added some documentation on how to shut it up if wanted.

https://github.com/jquense/teaspoon#build-warnings-with-webpack
