### ISSUE TITLE
teaspoon with wallaby.js

### ISSUE THREAD

**Issue by cellog** [jquense/teaspoon#44]
Hi,

I'm stumped with getting teaspoon to work with wallaby.js

on the "import teaspoon from 'teaspoon'" line in my test setup file, it fails with this cryptic error:

TypeError: Invalid Version: function (e) {var n=t[o][1][e];return s(n?n:e);}

Have you ever seen anything like this?  How do I even begin to debug this?

**Comment by jquense** [comment]
i haven't seen anything like this personally. can you provide an unminified stack trace?

**Comment by cellog** [comment]
the stack trace is unhelpful:

TypeError: Invalid Version: function (e) {var n=t[o][1][e];return s(n?n:e);}
	at test/test_helper.js:8
	at test/campers/components/Campers.test.js:1

the line in question is:

import teaspoon from 'teaspoon'

so... :)

I guess what I need to know is how teaspoon magically connects to jquery?  I couldn't discern it by a quick look over the code.  If I knew where to look, I might be able to find the answer.

**Comment by jquense** [comment]
that might be your problem...it doesn't actually connect to jQuery, or use jquery at all. its merely "jQuery like" in terms of it's api.

**Comment by cellog** [comment]
ok, so does it conflict with jQuery at all?  I am also using chai-jquery

**Comment by jquense** [comment]
it shouldn't, it doesn't set any global variables or mess with any either

**Comment by cellog** [comment]
I traced the error as being thrown in SemVer node package.  Apparently a version is being passed in that is not a string, but is that odd function.  It's obviously something where teaspoon is interacting with webpack, not sure what though.

**Comment by cellog** [comment]
I traced the error, it is being thrown in the SemVer package, which is not used by teaspoon. It's used by PouchDB. Basically, I fixed the problem by discarding everything I have tried to make wallaby work with webpack for the past 24 hours, and doing something else. Still no idea what the hell was going on. Too much magic! :)
