### ISSUE TITLE
Is there any way to test that a component returns null

### ISSUE THREAD

**Issue by nackjicholson** [jquense/teaspoon#51]
```js
export default function Foo(props) {
  if (!props.data) {
    return null;
  }

  return <pre>{JSON.stringify(props.data, null, 2)}</pre>;
}
```

Is there any way to assert that `$(<Foo/>).shallowRender()` has rendered and returned a "null" component?

Here is a work around I'm using which is fine.

```js
assert(Foo({}) === null)
```

Cheers 🍻

**Comment by jquense** [comment]
Can't think of any way off the top of my head... Not sure how to test this. Open to a PR tho :)
