### ISSUE TITLE
Teaspoon 6.6.0 is failing builds.

### ISSUE THREAD

**Issue by nackjicholson** [jquense/teaspoon#54]
We had a dependency on `^6.4.3` and our travis build is building with 6.6.0 and it's causing a majority of tests to fail. Claiming `"props" is undefined` and `_instance is null`

Also we're still running react `15.x`, I don't know if that could be the problem.

We set our dependency to `6.5.x` and the build passes.

**Comment by michellejzh** [comment]
![screen shot 2017-09-26 at 9 34 25 am](https://user-images.githubusercontent.com/6444775/30872321-847e7580-a29e-11e7-9dd2-60f908547f38.png)

Here is a screenshot of the issue described above.

**Comment by nackjicholson** [comment]
Closing. This is stale, and teaspoon has been deprecated.
