### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by jquense** [jquense/teaspoon#55]
Hey folks @nackjicholson et all, I've been playing around with enzyme 3.0 which supports full css selectors and I think it may be time to deprecate teaspoon and suggest Enzyme as it's api is almost completely compatible with teaspoon at this point. 

thoughts?

**Comment by nackjicholson** [comment]
I've been thinking the same thing sir! I've loved using teaspoon, and for a long time it was a better interface for doing component testing than enzyme, but that project has evolved a lot (and probably incorporated more of your `$` approach) so maybe with all the momentum it has it's best to just move over.

Thanks a ton for the work, this has been a truly superb library. I will definitely keep using it until we can migrate away, but if you decide to officially deprecate I'll add it to my tech debt backlog.

**Comment by nackjicholson** [comment]
@azizsyed I don't know if you're still using teaspoon to test at Nike, but thought I'd give you a heads up of this discussion in case you wanted to think about a migration to enzyme as well.

**Comment by azizsyed** [comment]
Thanks for the heads up @nackjicholson! We're still using it at the moment, but like you also mentioned we'll revisit our testing approach if teaspoon does indeed end up deprecated.

**Comment by walteranderson** [comment]
Hey @jquense I just wanted to say thank you for all your hard work on this library. I haven't been using it too long, but it has made component testing a breeze compared to what I had to deal with before ^_^

You mention in the readme that the API is close to parity, but that there are still a few differences. Is there a list of those differences somewhere?
