### ISSUE TITLE
nth-child

### ISSUE THREAD

**Issue by kristian-puccio** [jquense/teaspoon#9]
I'm query a list of li using .find and am wondering how get the nth-child.

I tried :nth-child and get the error psuedo element: nth-child is not supported.
I also tried ` el.find('li')[1] and I get undefined returned.

Thanks

**Comment by jquense** [comment]
the find method is correct, if 1 is undefined then it didn't find more than 1 li tag. not knowing the structure of you components tho it's hard to tell

**Comment by kristian-puccio** [comment]
sorry I should have given an example.

Say you have 
```<ul>
<li>one</li>
<li>two</li>
<li>three</li>
</ul>```

how do I get the text of the li element with two in it or trigger an action on it?

**Comment by jquense** [comment]
```js
let $els = $(<ul>
  <li>one</li>
  <li>two</li>
  <li>three</li>
</ul>)

$($el.children()[1]).text()
```

It's not the prettiest but there ya go, it wouldn't be hard to actually implement `:nth-child` but I just haven't had the time recently.

**Comment by kristian-puccio** [comment]
Cheers thanks. 
I had to change the selector to target the parent not the children, then it works perfectly.
